import type { AppProps } from "next/app";
import { MantineProvider } from "@mantine/core";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>India Ultimate Scores</title>
				<meta
					name="description"
					content="Generated by India Ultimate scores"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MantineProvider
				withGlobalStyles
				withNormalizeCSS
				theme={{
					/** Put your mantine theme override here */
					colorScheme: "dark",
				}}
			>
				<Component {...pageProps} />
			</MantineProvider>
		</>
	);
}
